### ISSUE TITLE
Volume isn't set to announce volume

### ISSUE THREAD

**Issue by SiebeVE** [TheFes/Google-Home-Resume#22]
[trace script.google_home_resume 2025-04-28T11_54_16.473675+00_00.json](https://github.com/user-attachments/files/19939458/trace.script.google_home_resume.2025-04-28T11_54_16.473675%2B00_00.json)

I'm running an automation that should announce a variable text received from the triggered event.
This is working nicely, apart that it doesn't change the volume to the set 0.75.

Anyone a clue what I'm doing wrong?

```
actions:
  - if:
      - condition: template
        value_template: "{{ trigger.event.data.rewardText is defined }}"
    then:
      - alias: Send TTS using Google Home Resume script
        action: script.turn_on
        target:
          entity_id: script.google_home_resume
        data:
          variables:
            action:
              - alias: Send TTS message
                action: tts.speak
                target:
                  entity_id: tts.piper
                data:
                  cache: true
                  media_player_entity_id: media_player.kantoor
                  message: "{{trigger.event.data.rewardText}}"
                extra:
                  volume: 0.75
```

My config:
```
homeassistant:
  customize:
    script.google_home_resume:
      # enter settings for the script here, all settings are optional, you can remove sections if you don't need them
      # always leave the line with "settings: &settings" in!
      settings: &settings
        speaker_groups:
          media_player.kantoor:
            - media_player.eetkamer
            - media_player.werkplek
        default_volume_level: 0.25
        default_resume_delay:
          seconds: 20
        max_runtime:
          minutes: 10
        stop_before_action: false
        # settings for automation
        enable_automation: false
        dashboard_cast: true
        announce_volume_automation: 0.75
      # settings for voice script
      voice_settings: &voice_settings
        use_resume: true
```

I've added the trace, but it doesn't look like it is the complete one?

**Comment by TheFes** [comment]
Hmm, there indeeds seems to be something wrong there. It tried to set the volume, but there is no target
```json
              "domain": "media_player",
              "service": "volume_set",
              "service_data": {
                "volume_level": 0.75,
                "entity_id": []
              },
              "target": {
                "entity_id": []
              }
```
I'll look into it.

**Comment by TheFes** [comment]
Ah right!

Try this:
```yaml
actions:
  - if:
      - condition: template
        value_template: "{{ trigger.event.data.rewardText is defined }}"
    then:
      - alias: Send TTS using Google Home Resume script
        action: script.turn_on
        target:
          entity_id: script.google_home_resume
        data:
          variables:
            target:
              entity_id: media_player.kantoor
            action:
              - alias: Send TTS message
                action: tts.speak
                target:
                  entity_id: tts.piper
                data:
                  cache: true
                  media_player_entity_id: media_player.kantoor
                  message: "{{trigger.event.data.rewardText}}"
                extra:
                  volume: 0.75
```

**Comment by SiebeVE** [comment]
Unfortunately this doesn't work for me either.

[trace script.google_home_resume 2025-05-05T11_00_32.355627+00_00.json](https://github.com/user-attachments/files/20035153/trace.script.google_home_resume.2025-05-05T11_00_32.355627%2B00_00.json)

**Comment by TheFes** [comment]
Then  try this:
```yaml
actions:
  - if:
      - condition: template
        value_template: "{{ trigger.event.data.rewardText is defined }}"
    then:
      - alias: Send TTS using Google Home Resume script
        action: script.turn_on
        target:
          entity_id: script.google_home_resume
        data:
          variables:
            action:
              - alias: Send TTS message
                action: tts.speak
                target:
                  entity_id: tts.piper
                data:
                  cache: true
                  media_player_entity_id: media_player.kantoor
                  message: "{{trigger.event.data.rewardText}}"
                extra:
                  # the entity id is now provided here, this is also taken into account when applying the volume
                  entity_id: media_player.kantoor
                  volume: 0.75
```
