### ISSUE TITLE
Not annoucing, no errors

### ISSUE THREAD

**Issue by iDVB** [TheFes/Google-Home-Resume#5]
I have setup Spotify and Spotcast as well as this script as a pacakge setup, however, it does not seem to work. 

It is not erroring out but its also **not** announcing on the Google Home device. The Google Home device makes a notification noise like something will happen, even stops the playing music... but then does not speak anything out.

Not sure is I'm even using the script correctly, are we supposed to check if something is playing and only use this script if YES... otherwise just call tts.google_cloud_say ourselves?

Here is the automation I'm manually running as a test....
```
description: Announce if the patio door is open every 15 minutes
trigger: []
condition: []
action:
  - service: script.turn_on
    target:
      entity_id: script.google_home_resume
    data:
      variables:
        action:
          - alias: Send TTS message
            service: tts.google_cloud_say
            target:
              entity_id: media_player.family_room_speaker
            data:
              message: A patio door may have been left open. Please fully close.
            extra:
              volume: 0.6
mode: restart

```
