### ISSUE TITLE
automation.00_google_home_automatic_resume makes "normal" TTS unusable due to Volume on 100%

### ISSUE THREAD

**Issue by itspuia** [TheFes/Google-Home-Resume#6]
When the Automation "automation.00_google_home_automatic_resume" is activated, the "normal" TTS Scripts e.g. from tts.cloud_say (When not using your script) will play the TTS on full volume. Whatever I do, both in YAML or in NodeRed TTS is unusable if the automation is activated.

Deactivating your Automation works. TTS is in normal (unchanged) volume again.
So far doesn't bother the other automations so far. So I deactivated it. Will I "need" it in the future?

**Comment by itspuia** [comment]
One day later and when disabling this automation a lot of Google Home Resume service calls aren't working correctly anymore unfortunately. 
So I either can only use the "normal" tts calls without resuming but in a normal Volume
or I can only use the Google Home Resume Script only.

**Comment by TheFes** [comment]
With the automation activated, it will apply the `announce_volume_automation` to everything sent with `announce: true`.
So it will apply this to all TTS messages, regardless which integration is used and which service call. This is because the TTS service call will send the message to the media player with `announce: true`

**Comment by TheFes** [comment]
I'm not sure what you mean with Google Resume service calls, can you give an example?

BTW I actually advice to disable the automation in the Readme. It's disabled in the example settings as well

**Comment by itspuia** [comment]
> what you mean with Google Resume service calls

Hi @TheFes and thank you for your reply!

By Google Resume service call I simply mean calling your script instead of the normal TTS.

Ever since I disabled it, some of my TTS aren't working properly anymore.

So far basically every TTS Message I send is made with your Google Resume Service call:

```
service: script.google_home_resume
data:
  target:
    entity_id: media_player.nest_schlafzimmer
  action:
    - service: tts.cloud_say
      metadata: {}
      data:
        cache: false
        entity_id: media_player.nest_schlafzimmer
        message: Test Message
```

When the mentioned automation is turned on, calling this service instead will always result in a 100% Volume:

```
service: tts.cloud_say
data:
  cache: false
  entity_id: media_player.nest_schlafzimmer
  message: Test Message
```

The reason I actually disabled it is to use it in node Red. I couldn't find an example on how to use your script in node red. If there is a simple service call, I can use that instead and enable the automation again.

What should I do in your opinion?
